{
 "title": "Authentication Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "User Registration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(registration_new_total[1m])",
     "legendFormat": "User Registered"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "graph",
   "description": "authentication success and failure",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(authentication_successful_total[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(authentication_failed_total[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Passwords",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(password_changed_total[5m])",
     "legendFormat": "password changed"
    },
    {
     "expr": "rate(password_recovered_total[5m])",
     "legendFormat": "password recovered"
    }
   ]
  }
 ]
}